development:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

test:
  adapter: test

staging:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>

production:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "any_cable") %>
