default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 10000
  username: arsood

development:
  <<: *default
  database: meetingzero_development

staging:
  <<: *default
  database: meetingzero_staging
  username: postgres
  password: Password@1

test:
  <<: *default
  database: meetingzero_test

production:
  <<: *default
  database: meetingzero_production
  username: postgres
  password: <%= Rails.application.credentials.rds_master_password %>
  host: <%= Rails.application.credentials.rds_endpoint %>
